export type productDataType = {
    id: number,
    name: string,
    description: string,
    price: number,
    unit: string,
    stock: number,
    created_at: number,
}

export const productData: productDataType[] = [
    {
        id: 1,
        name: 'Product 1',
        description: 'Description of product 1',
        price: 100,
        unit: 'pcs',
        stock: 100,
        created_at: new Date('2021-01-01').getTime(),
    },
    {
        id: 2,
        name: 'Product 2',
        description: 'Description of product 2',
        price: 200,
        unit: 'pcs',
        stock: 50,
        created_at: new Date('2021-02-01').getTime(),
    },
    {
        id: 3,
        name: 'Product 3',
        description: 'Description of product 3',
        price: 150,
        unit: 'pcs',
        stock: 75,
        created_at: new Date('2021-03-01').getTime(),
    },
    {
        id: 4,
        name: 'Product 4',
        description: 'Description of product 4',
        price: 250,
        unit: 'pcs',
        stock: 30,
        created_at: new Date('2021-04-01').getTime(),
    },
    {
        id: 5,
        name: 'Product 5',
        description: 'Description of product 5',
        price: 300,
        unit: 'pcs',
        stock: 20,
        created_at: new Date('2021-05-01').getTime(),
    },
    {
        id: 6,
        name: 'Product 6',
        description: 'Description of product 6',
        price: 350,
        unit: 'pcs',
        stock: 10,
        created_at: new Date('2021-06-01').getTime(),
    },
    {
        id: 7,
        name: 'Product 7',
        description: 'Description of product 7',
        price: 400,
        unit: 'pcs',
        stock: 5,
        created_at: new Date('2021-07-01').getTime(),
    },
    {
        id: 8,
        name: 'Product 8',
        description: 'Description of product 8',
        price: 450,
        unit: 'pcs',
        stock: 2,
        created_at: new Date('2021-08-01').getTime(),
    },
    {
        id: 9,
        name: 'Product 9',
        description: 'Description of product 9',
        price: 500,
        unit: 'pcs',
        stock: 1,
        created_at: new Date('2021-09-01').getTime(),
    },
    {
        id: 10,
        name: 'Product 10',
        description: 'Description of product 10',
        price: 550,
        unit: 'pcs',
        stock: 0,
        created_at: new Date('2021-10-01').getTime(),
    },
]